version: '3.8'

services:
  todolist:
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:5181

    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5181:5181"
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    container_name: ${POSTGRES_HOST}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} 
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"

volumes:
  pgdata: